version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1111
    ports:
      - "8080:80"
    depends_on:
      - db

  node:
    build:
      context: ./node-app
    ports:
      - "3001:3000"
    volumes:
      - ./node-app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

volumes:
  db_data:
